language: node_js
node_js:
    - 12

services:
  - postgresql
    
  addons:
    postgresql: '12'
    apt:
        packages:
            - postgresql-12
            - postgresql-client-12

    env:
        global:
            -PGPORT=5432
            -DB_NAME=users
            -DB_USER=postgres
            -DB_PASSWORD='mthobisi'

  before_script:
  - psql --command='create user ${DB_USER};'
  - psql --command='create database ${DB_NAME} WITH OWNER = ${DB_USER};'
  - psql --dbname=${DB_NAME} --file=table.sql

  install:
    npm install
  cache:
    directories:
        - 'node_modules'
